import { describe, expect, test } from "bun:test"
import { commandMarker, hasManagedMarker, MANAGED_COMMAND_NAMES, renderCommandTemplate } from "../src/templates"

describe("command templates", () => {
  test("renders /copaper in Chinese by default", () => {
    const output = renderCommandTemplate("copaper")
    expect(output).toContain("<!-- CoPaper managed: @copaper/opencode; command=copaper; schemaVersion=1 -->")
    expect(output).toContain("description: 显示 CoPaper 项目仪表盘")
    expect(output).toContain("copaper_dashboard")
    expect(output).toContain("/copaper-doctor")
    expect(output).toContain("/copaper-relatedwork")
    expect(output).toContain("bunx -p @copaper/opencode copaper-opencode doctor")
    expect(output).toContain("确认初始化")
    expect(output).toContain("项目名称")
    expect(output).toContain("研究领域")
    expect(output).toContain("每次调用 CoPaper 工具后")
    expect(output).toContain("展示工具返回的人类可读 markdown 正文和表格")
    expect(output).toContain("默认不要展示 fenced JSON block")
    expect(output).toContain("用户明确要求 JSON、debug 或原始输出时才展示")
    expect(output).toContain("不要只总结工具结果")
    expect(output).toContain("question tool")
    expect(output).toContain("询问是否初始化")
    expect(output).toContain("收集项目名称和研究领域")
    expect(output).toContain("copaper_init_apply")
    expect(output).toContain("copaper_artifact_status")
    expect(output).toContain("copaper_artifact_record")
    expect(output).toContain("工件状态")
    expect(output).toContain("只读")
    expect(output).toContain("复述 artifact、status、confidence 和 reason")
    expect(output).toContain("不会自动推进 phase")
    expect(output).toContain("不会运行 checker/relatedwork/report/git/skills 动作")
    expect(output).toContain("copaper_workflow_status")
    expect(output).toContain("copaper_workflow_log")
    expect(output).toContain("copaper_workflow_set_phase")
    expect(output).toContain("修改阶段状态")
    expect(output).toContain("等待用户确认")
    expect(output).toContain("只能使用工具返回的信息")
    expect(output).toContain("不要编造 CoPaper 状态")
    expect(output).toContain("@copaper-coordinator")
    expect(output).toContain("@copaper-storyline")
    expect(output).toContain("@copaper-writer")
    expect(output).toContain("@copaper-reviewer")
    expect(output).toContain("@copaper-recorder")
    expect(output).toContain("@copaper-literature")
    expect(output).toContain("agent profile")
    expect(output).not.toContain("copaper_relatedwork_search")
    expect(output).not.toContain("copaper --root <root> relatedwork")
    expect(output).not.toContain("!`")
  })

  test("renders /copaper in English when requested", () => {
    const output = renderCommandTemplate("copaper", "en-US")
    expect(output).toContain("description: Show CoPaper project dashboard")
    expect(output).toContain("/copaper-relatedwork")
    expect(output).toContain("confirm initialization")
    expect(output).toContain("project name")
    expect(output).toContain("research domain")
    expect(output).toContain("After each CoPaper tool call")
    expect(output).toContain("show the human-readable markdown body and tables")
    expect(output).toContain("omit fenced JSON blocks by default")
    expect(output).toContain("only show JSON when the user explicitly asks for JSON, debug, raw output, or full tool output")
    expect(output).toContain("do not summarize tool results instead")
    expect(output).toContain("question tool")
    expect(output).toContain("ask whether to initialize")
    expect(output).toContain("collect the project name and research domain")
    expect(output).toContain("copaper_init_apply")
    expect(output).toContain("copaper_artifact_status")
    expect(output).toContain("copaper_artifact_record")
    expect(output).toContain("artifact status")
    expect(output).toContain("read-only")
    expect(output).toContain("restate the artifact, status, confidence, and reason")
    expect(output).toContain("does not automatically advance phases")
    expect(output).toContain("does not automatically advance phases or run checker/relatedwork/report/git/skills actions")
    expect(output).toContain("copaper_workflow_status")
    expect(output).toContain("copaper_workflow_log")
    expect(output).toContain("copaper_workflow_set_phase")
    expect(output).toContain("change a phase status")
    expect(output).toContain("wait for confirmation")
    expect(output).toContain("Only use information returned by tools")
    expect(output).toContain("Do not invent CoPaper status")
    expect(output).toContain("@copaper-coordinator")
    expect(output).toContain("@copaper-storyline")
    expect(output).toContain("@copaper-writer")
    expect(output).toContain("@copaper-reviewer")
    expect(output).toContain("@copaper-recorder")
    expect(output).toContain("@copaper-literature")
    expect(output).toContain("agent profile")
    expect(output).not.toContain("copaper_relatedwork_search")
    expect(output).not.toContain("copaper --root <root> relatedwork")
  })

  test("renders /copaper-doctor in Chinese by default", () => {
    const output = renderCommandTemplate("copaper-doctor")
    expect(output).toContain("<!-- CoPaper managed: @copaper/opencode; command=copaper-doctor; schemaVersion=1 -->")
    expect(output).toContain("description: 诊断 CoPaper OpenCode 插件安装")
    expect(output).toContain("bunx -p @copaper/opencode copaper-opencode doctor --format markdown 2>&1 || true")
    expect(output).toContain("原样显示输出")
    expect(output).toContain("agent profile diagnostics")
    expect(output).not.toContain("bunx @copaper/opencode doctor")
    expect(output).not.toContain("$ARGUMENTS")
  })

  test("renders /copaper-doctor in English with agent diagnostics", () => {
    const output = renderCommandTemplate("copaper-doctor", "en-US")
    expect(output).toContain("agent profile diagnostics")
  })

  test("renders /copaper-relatedwork in Chinese by default", () => {
    const output = renderCommandTemplate("copaper-relatedwork")
    expect(output).toContain("<!-- CoPaper managed: @copaper/opencode; command=copaper-relatedwork; schemaVersion=1 -->")
    expect(output).toContain("description: 驱动 CoPaper 相关工作")
    expect(output).toContain("copaper_relatedwork_status")
    expect(output).toContain("copaper_relatedwork_keywords")
    expect(output).toContain("只读工具（无需确认）：`copaper_relatedwork_status`")
    expect(output).toContain("写盘工具（必须复述完整参数，等待用户明确确认后才可调用）：`copaper_relatedwork_keywords`")
    expect(output).toContain("`keywords` 会通过 Python CLI 写入 `relatedwork/queries.txt`")
    expect(output).toContain("不会额外追加插件侧 phase-patch 事件")
    expect(output).toContain("copaper_relatedwork_search")
    expect(output).toContain("copaper_relatedwork_import")
    expect(output).toContain("copaper_relatedwork_sync_bib")
    expect(output).toContain("copaper_relatedwork_download")
    expect(output).toContain("copaper_relatedwork_summarize")
    expect(output).toContain("copaper_relatedwork_register_summary")
    expect(output).toContain("copaper_relatedwork_build_index")
    expect(output).toContain("copaper_relatedwork_clean")
    expect(output).toContain("@copaper-literature")
    expect(output).toContain("copaper_workflow_set_phase")
    expect(output).toContain("phase=literature")
    expect(output).toContain("status=complete")
    expect(output).toContain("copaper-cli-unavailable")
    expect(output).toContain("uv pip install -e .")
    expect(output).toContain("/copaper-doctor")
    expect(output).not.toContain("copaper --root <root> relatedwork")
    expect(output).not.toContain("!`")
  })

  test("renders /copaper-relatedwork in English when requested", () => {
    const output = renderCommandTemplate("copaper-relatedwork", "en-US")
    expect(output).toContain("description: Drive the CoPaper relatedwork")
    expect(output).toContain("copaper_relatedwork_status")
    expect(output).toContain("copaper_relatedwork_keywords")
    expect(output).toContain("Read-only tools (no confirmation required): `copaper_relatedwork_status`")
    expect(output).toContain("Write tools (must restate every argument and wait for explicit user confirmation before calling): `copaper_relatedwork_keywords`")
    expect(output).toContain("`keywords` writes `relatedwork/queries.txt` through the Python CLI")
    expect(output).toContain("does not add an extra plugin-side phase-patch event")
    expect(output).toContain("copaper_relatedwork_search")
    expect(output).toContain("copaper_relatedwork_import")
    expect(output).toContain("copaper_relatedwork_sync_bib")
    expect(output).toContain("copaper_relatedwork_download")
    expect(output).toContain("copaper_relatedwork_summarize")
    expect(output).toContain("copaper_relatedwork_register_summary")
    expect(output).toContain("copaper_relatedwork_build_index")
    expect(output).toContain("copaper_relatedwork_clean")
    expect(output).toContain("@copaper-literature")
    expect(output).toContain("copaper_workflow_set_phase")
    expect(output).toContain("phase=literature")
    expect(output).toContain("status=complete")
    expect(output).toContain("copaper-cli-unavailable")
    expect(output).toContain("uv pip install -e .")
    expect(output).not.toContain("copaper --root <root> relatedwork")
  })

  test("detects CoPaper-managed command markers", () => {
    const marker = commandMarker("copaper")
    expect(marker).toBe("<!-- CoPaper managed: @copaper/opencode; command=copaper; schemaVersion=1 -->")
    expect(hasManagedMarker(`${marker}\nbody`, "copaper")).toBe(true)
    expect(hasManagedMarker("# custom command", "copaper")).toBe(false)
    expect(hasManagedMarker(commandMarker("copaper-doctor"), "copaper")).toBe(false)
    expect(hasManagedMarker(commandMarker("copaper-relatedwork"), "copaper-relatedwork")).toBe(true)
    expect(hasManagedMarker(commandMarker("copaper-relatedwork"), "copaper")).toBe(false)
  })

  test("MANAGED_COMMAND_NAMES includes all three managed commands", () => {
    expect([...MANAGED_COMMAND_NAMES]).toEqual(["copaper", "copaper-doctor", "copaper-relatedwork"])
  })
})
