import { describe, expect, test } from "bun:test"
import { commandMarker, hasManagedMarker, renderCommandTemplate } from "../src/templates"

describe("command templates", () => {
  test("renders /vibe in Chinese by default", () => {
    const output = renderCommandTemplate("vibe")
    expect(output).toContain("<!-- VibePaper managed: @vibepaper/opencode; command=vibe; schemaVersion=1 -->")
    expect(output).toContain("description: 显示 VibePaper 项目仪表盘")
    expect(output).toContain("vibepaper_dashboard")
    expect(output).toContain("/vibe-doctor")
    expect(output).toContain("bunx -p @vibepaper/opencode vibepaper-opencode doctor")
    expect(output).toContain("确认初始化")
    expect(output).toContain("项目名称")
    expect(output).toContain("研究领域")
    expect(output).toContain("每次调用 VibePaper 工具后")
    expect(output).toContain("展示工具返回的人类可读 markdown 正文和表格")
    expect(output).toContain("默认不要展示 fenced JSON block")
    expect(output).toContain("用户明确要求 JSON、debug 或原始输出时才展示")
    expect(output).toContain("不要只总结工具结果")
    expect(output).toContain("question tool")
    expect(output).toContain("询问是否初始化")
    expect(output).toContain("收集项目名称和研究领域")
    expect(output).toContain("vibepaper_init_apply")
    expect(output).toContain("vibepaper_artifact_status")
    expect(output).toContain("vibepaper_artifact_record")
    expect(output).toContain("工件状态")
    expect(output).toContain("只读")
    expect(output).toContain("复述 artifact、status、confidence 和 reason")
    expect(output).toContain("不会自动推进 phase")
    expect(output).toContain("不会运行 checker/relatedwork/report/git/skills 动作")
    expect(output).toContain("vibepaper_workflow_status")
    expect(output).toContain("vibepaper_workflow_log")
    expect(output).toContain("vibepaper_workflow_set_phase")
    expect(output).toContain("修改阶段状态")
    expect(output).toContain("等待用户确认")
    expect(output).toContain("只能使用工具返回的信息")
    expect(output).toContain("不要编造 VibePaper 状态")
    expect(output).toContain("@vibepaper-coordinator")
    expect(output).toContain("@vibepaper-storyline")
    expect(output).toContain("@vibepaper-writer")
    expect(output).toContain("@vibepaper-reviewer")
    expect(output).toContain("@vibepaper-recorder")
    expect(output).toContain("agent profile")
    expect(output).not.toContain("!`")
  })

  test("renders /vibe in English when requested", () => {
    const output = renderCommandTemplate("vibe", "en-US")
    expect(output).toContain("description: Show VibePaper project dashboard")
    expect(output).toContain("confirm initialization")
    expect(output).toContain("project name")
    expect(output).toContain("research domain")
    expect(output).toContain("After each VibePaper tool call")
    expect(output).toContain("show the human-readable markdown body and tables")
    expect(output).toContain("omit fenced JSON blocks by default")
    expect(output).toContain("only show JSON when the user explicitly asks for JSON, debug, raw output, or full tool output")
    expect(output).toContain("do not summarize tool results instead")
    expect(output).toContain("question tool")
    expect(output).toContain("ask whether to initialize")
    expect(output).toContain("collect the project name and research domain")
    expect(output).toContain("vibepaper_init_apply")
    expect(output).toContain("vibepaper_artifact_status")
    expect(output).toContain("vibepaper_artifact_record")
    expect(output).toContain("artifact status")
    expect(output).toContain("read-only")
    expect(output).toContain("restate the artifact, status, confidence, and reason")
    expect(output).toContain("does not automatically advance phases")
    expect(output).toContain("does not automatically advance phases or run checker/relatedwork/report/git/skills actions")
    expect(output).toContain("vibepaper_workflow_status")
    expect(output).toContain("vibepaper_workflow_log")
    expect(output).toContain("vibepaper_workflow_set_phase")
    expect(output).toContain("change a phase status")
    expect(output).toContain("wait for confirmation")
    expect(output).toContain("Only use information returned by tools")
    expect(output).toContain("Do not invent VibePaper status")
    expect(output).toContain("@vibepaper-coordinator")
    expect(output).toContain("@vibepaper-storyline")
    expect(output).toContain("@vibepaper-writer")
    expect(output).toContain("@vibepaper-reviewer")
    expect(output).toContain("@vibepaper-recorder")
    expect(output).toContain("agent profile")
  })

  test("renders /vibe-doctor in Chinese by default", () => {
    const output = renderCommandTemplate("vibe-doctor")
    expect(output).toContain("<!-- VibePaper managed: @vibepaper/opencode; command=vibe-doctor; schemaVersion=1 -->")
    expect(output).toContain("description: 诊断 VibePaper OpenCode 插件安装")
    expect(output).toContain("bunx -p @vibepaper/opencode vibepaper-opencode doctor --format markdown 2>&1 || true")
    expect(output).toContain("原样显示输出")
    expect(output).toContain("agent profile diagnostics")
    expect(output).not.toContain("bunx @vibepaper/opencode doctor")
    expect(output).not.toContain("$ARGUMENTS")
  })

  test("renders /vibe-doctor in English with agent diagnostics", () => {
    const output = renderCommandTemplate("vibe-doctor", "en-US")
    expect(output).toContain("agent profile diagnostics")
  })

  test("detects VibePaper-managed command markers", () => {
    const marker = commandMarker("vibe")
    expect(marker).toBe("<!-- VibePaper managed: @vibepaper/opencode; command=vibe; schemaVersion=1 -->")
    expect(hasManagedMarker(`${marker}\nbody`, "vibe")).toBe(true)
    expect(hasManagedMarker("# custom command", "vibe")).toBe(false)
    expect(hasManagedMarker(commandMarker("vibe-doctor"), "vibe")).toBe(false)
  })
})
